//@entrypoint=https://eco-roads.herokuapp.com/api/v1
@entrypoint=http://localhost:5000/api/v1

@accessToken=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhMjZkYWZhLTRjNzItNDMzZi1iYTdiLWNjMmQ4NDI3MTJjNiIsImVtYWlsIjoiem9yb0BnbWFpbC5jb20iLCJ1c2VybmFtZSI6IlJvcm9ubyIsImxvY2F0aW9uX2lkIjo4MiwiY2FyX2lkIjo5LCJjcmVhdGVkX2F0IjoiMjAyMi0wOC0wNlQxMjoxNToyOS4wODdaIiwidXBkYXRlZF9hdCI6bnVsbCwiaWF0IjoxNjU5Nzg4MTQ3LCJleHAiOjE2NTk3ODkzNDd9.fJTi-klJTpZNHmrC8o1j48FZLH-Q0oA3iMM_PrgYYzA



@refreshToken=Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmMGRkZjBiLWEwYWEtNGE0MC1iM2VlLWNkMzQwNTkzOTEyYiIsImVtYWlsIjoidGVzdDEwQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidGVzdCIsImxvY2F0aW9uX2lkIjoxMywiY2FyX2lkIjoxMiwiY3JlYXRlZF9hdCI6IjIwMjItMDgtMDFUMTc6NDg6MzMuMzY1WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY1OTM3NjI3NCwiZXhwIjoxNjU5Mzc2NTc0fQ.RU55u7c4WvkGG2kBvPxddY21VIRNKlTP7DbOa03hBPA

# @refreshedAccessToken= Authorization:  Bearer 

##  ------------------------------------------------------------- MAPS
## --------------------------------------------------------------------
###
GET {{entrypoint}}/team

###
POST {{entrypoint}}/map
Content-Type: application/json

{
        "categories": [4,5,6],
        "car_id": 8,
        "location":{
            "label": "25 rue de Fort Boyard, 17000 La Rochelle",
            "address": "Rue de Fort Boyard",
            "street_number": 15,
            "zipcode": 17000,
            "city": "La Rochelle",
            "Lat": 46.33342424379,
            "Long": -1.3047137072481991
    },
    "arrival": {
            "label": "108 rue de bellevue, 33000 Bordeaux",
            "address": "Rue de bellevue",
            "street_number": 108,
            "zipcode": 33000,
            "city": "Bordeaux",

            "Lat": 44.9232823983815,
            "Long": -0.23967107651036118

    }
}


###
##--------------------------------------------------------------- USERS
## ---------------------------------------------------------------------

GET {{entrypoint}}/users

###
POST {{entrypoint}}/user/register
Content-Type: application/json

{
    "email": "zoro@gmail.com",
    "password": "Onepiece63!",
    "username": "Rorono",
    "car_id": 9,
        "location":{
        "label": " 25 Grand line, 83100 South Blue",
        "address": "Grand Line Sea",
        "street_number": 2,
        "zipcode": 83000,
        "city": "East Blue",
        "Lat": 41.94412898265,
        "Long": -2.121549756121
    },
    "arrival":{
        "address": "Grand Line Sea",
        "street_number": 2,
        "zipcode": 83000,
        "city": "East Blue",
        "Lat": 46.94412898265,
        "Long": -2.121549756121
    },
    "categories": [4,5]
}

###
POST {{entrypoint}}/user/login
Content-Type: application/json

{
    "email": "zoro@gmail.com",
    "password": "Onepiece63!"
}

###
GET {{entrypoint}}/user/profile
Content-Type: application/json
{{accessToken}}


###
GET {{entrypoint}}/refresh_token


###
PATCH {{entrypoint}}/user/profile
{{accessToken}}
Content-Type: application/json

{
        "location":{
        "label": " 25 Grand line, 83100 South Blue",
        "address": "Grand Line Sea",
        "street_number": 2,
        "zipcode": 83000,
        "city": "East Blue",
        "Lat": 41.94412898265,
        "Long": -2.121549756121
        },
    "categories": [4,5,6]
}

### 
DELETE {{entrypoint}}/user/profile
{{accessToken}}
Content-Type: application/json

###
GET {{entrypoint}}/user/logout


###
GET {{entrypoint}}/cars

###
GET {{entrypoint}}/car/17

##--------------------------------------------------------------- CATEGORIES
## --------------------------------------------------------------------------

###
GET {{entrypoint}}/categories

###
GET {{entrypoint}}/category/1



###
POST {{entrypoint}}/cars

###
PATCH {{entrypoint}}/car/:id

###
DELETE {{entrypoint}}/car/:id



##--------------------------------------------------------------- LOCATION
## ---------------------------------------------------------------------

##--------------------------------------------------------------- NETWORK
## ---------------------------------------------------------------------

##--------------------------------------------------------------- ROADS
## ---------------------------------------------------------------------