@entrypoint=https://eco-roads.herokuapp.com/api/v1

##--------------------------------------------------------------- USERS
## ---------------------------------------------------------------------



GET {{entrypoint}}/users

###
POST {{entrypoint}}/user/register
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "helloo",
    "username": "test",
}

###
POST {{entrypoint}}/user/login
Content-Type: application/json

{
    "email": "gaetan@gmail.com",
    "password": "helloo"
}

###
GET {{entrypoint}}/user/logout

###
GET {{entrypoint}}/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcwMThmZjcyLWViYWEtNDc0Mi04Y2RmLWFhYzAzNjA3YWEyYiIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDcvdmtJbGFxcGNrcE1ObGZRdmU3aS4vaEU3ZVcyMm90anNBZWd4TjBGZS9DYnhuNHE2dERDIiwidXNlcm5hbWUiOiJ0ZXN0IiwibG9jYXRpb25faWQiOjEsImNhcl9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjItMDctMjJUMTY6MDM6MDAuODUzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY1ODUwODkyOCwiZXhwIjoxNjU4NTEwNzI4fQ.RxS8vHvvwYDXOdIJTihKBWzDp0mbV-L6bPSIYhyC7TM

###
PATCH {{entrypoint}}/user/profile

### 
DELETE {{entrypoint}}/user/profile

###
GET {{entrypoint}}/refresh_token

## --------------------------------------------------------------- CARS 
## ---------------------------------------------------------------------

###
GET {{entrypoint}}/cars

###
GET {{entrypoint}}/car/:id

###
POST {{entrypoint}}/cars

###
PATCH {{entrypoint}}/car/:id

###
DELETE {{entrypoint}}/car/:id

##--------------------------------------------------------------- CATEGORIES
## ---------------------------------------------------------------------

##--------------------------------------------------------------- LOCATION
## ---------------------------------------------------------------------

##--------------------------------------------------------------- NETWORK
## ---------------------------------------------------------------------

##--------------------------------------------------------------- ROADS
## ---------------------------------------------------------------------