-- Deploy ecoroads:01.init to pg

BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DOMAIN EMAIL AS TEXT CHECK ( value ~ '^[\w\-\.]+@([\w-]+\.)+[\w-]+$');

CREATE DOMAIN postal_code_fr AS text CHECK (
    -- 01000 à 09999
    VALUE ~ '0[1-9]\d{3}' 
    -- 10000 à 89999
    OR VALUE ~ '[1-8]\d{4}' 
    -- les numéros commençant par 9 en métropole
    OR VALUE ~ '9[0-6]\d{3}'
);



CREATE TABLE
    IF NOT EXISTS public."user"(
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "email" EMAIL UNIQUE NOT NULL,
        "password" TEXT NOT NULL,
        "username" TEXT NOT NULL,
        "location_id" INT NULL,
        "car_id" INT NULL,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."network"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "image" TEXT NULL,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."car"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "brand_id" INT NOT NULL,
        "model" TEXT NOT NULL UNIQUE,
        "image" TEXT NULL,
        "network_id" INT NULL REFERENCES "network" ("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );


CREATE TABLE
    IF NOT EXISTS public."location"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT NULL,
    "address" TEXT NOT NULL,
    "street_number" INT NULL,
    "zipcode" postal_code_fr NOT NULL,
    "city" TEXT NOT NULL,
    "lat" NUMERIC NOT NULL,
    "lon" NUMERIC NOT NULL
);

CREATE TABLE
    IF NOT EXISTS public."category"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "icon" TEXT NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );


CREATE TABLE
    IF NOT EXISTS public."charging_station" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "network_id" INT NULL REFERENCES "network" ("id"),
        "location_id" INTEGER NOT NULL REFERENCES "location"("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."interesting_point" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "description" TEXT NULL,
        "image" TEXT NULL,
        "eco_friendly" BOOLEAN DEFAULT FALSE,
        "category_id" INTEGER NOT NULL REFERENCES "category"("id"),
        "location_id" INTEGER NOT NULL REFERENCES "location"("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."road" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" uuid NOT NULL REFERENCES "user"("id"),
        "generated_road" JSON NULL,
        "favorite" BOOLEAN DEFAULT FALSE,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."user_like_category"(
        "category_id" integer REFERENCES "category"("id"),
        "user_id" uuid REFERENCES "user"("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

ALTER TABLE "user" ADD FOREIGN KEY ("car_id") REFERENCES "car"("id"); 
ALTER TABLE "user" ADD FOREIGN KEY ("location_id") REFERENCES "location"("id");



COMMIT;
