-- Deploy ecoroads:02.add_table_brand to pg

BEGIN;

CREATE TABLE
    IF NOT EXISTS public."brand"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );
ALTER TABLE "car" ADD FOREIGN KEY ("brand_id") REFERENCES "brand"("id"); 

COMMIT;
