-- Deploy ecoroads:01.init to pg

BEGIN;


CREATE DOMAIN EMAIL AS TEXT CHECK ( value ~ '^[\w\-\.]+@([\w-]+\.)+[\w-]+$');

CREATE TYPE "gps_coordinates" AS (
    "address" TEXT,
    "street_number" INT,
    "zipcode" NUMERIC,
    "city" TEXT,
    "lat" NUMERIC,
    "lon" NUMERIC
);


CREATE TABLE
    IF NOT EXISTS public."user"(
        "id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "email" EMAIL UNIQUE NOT NULL,
        "password" TEXT NOT NULL,
        "username" TEXT NULL,
        "location" gps_coordinates NULL,
        "car_id" INT NOT NULL,
        "category_id" INT NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."network"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."car"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "brand" TEXT NOT NULL UNIQUE,
        "model" TEXT NOT NULL UNIQUE,
        "image" TEXT,
        "network_id" INT NULL REFERENCES "network" ("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."category"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );


CREATE TABLE
    IF NOT EXISTS public."charging_station" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "location" gps_coordinates,
        "network_id" INT NULL REFERENCES "network" ("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."interesting_point" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "description" TEXT NULL,
        "location" gps_coordinates,
        "eco_friendly" BOOLEAN DEFAULT FALSE,
        "category_id" INTEGER NOT NULL REFERENCES "category"("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."road" (
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "favorite" BOOLEAN DEFAULT FALSE,
        "generated_road" TEXT NULL,
        "user_id" INTEGER NOT NULL REFERENCES "user"("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."user_like_category"(
        "category_id" integer REFERENCES "category"("id"),
        "user_id" integer REFERENCES "user" ("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

ALTER TABLE "user" ADD FOREIGN KEY ("car_id") REFERENCES "car"("id"); 
ALTER TABLE "user" ADD FOREIGN KEY ("category_id") REFERENCES "category"("id"); 



COMMIT;
