-- Deploy ecoroads:02.add_table_brand to pg

BEGIN;

TRUNCATE TABLE public.car CASCADE;
ALTER TABLE public.car RENAME COLUMN brand TO brand_id;
ALTER TABLE public.car ALTER COLUMN brand_id TYPE INT USING brand_id::integer;
CREATE TABLE
    IF NOT EXISTS public."brand"(
        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );
ALTER TABLE "car" ADD FOREIGN KEY ("brand_id") REFERENCES "brand"("id"); 

COMMIT;
